config/routes.rb
Task::Application.routes.draw do
  resources :tasktops

  devise_for :users
  

  root 'tasktops#top'

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/tasktop.rb
class Tasktop < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasktops
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
	  :recoverable, :rememberable, :trackable, :validatable
  
  def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
		  where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
		  where(conditions).first
	  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login, :username, :email, :password, :group) }
		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tasktops_controller.rb
# -*- encoding: utf-8 -*-
class TasktopsController < ApplicationController
	before_action :set_tasktop, only: [:show, :edit, :update, :destroy]

	# GET /tasktops
	# GET /tasktops.json
	def top
		#team_memberを作成
		@members = User.where(group: current_user.group)
		
		team_member = Array.new()
		team_member_id = Array.new()
		@members.each do |f|
			team_member.push(f.username)
			team_member_id.push(f.id)
		end

		#weight_listを作成
		weight_list = Array.new()
		sum = 0
		team_member_id.each do |f|
			sum = Tasktop.where(user_id: f).pluck(:weight).inject(:+)
			weight_list.push(sum)
		end
		p weight_list
		
		#pieグラフのデータ作成
		notyet_task = (Tasktop.where(user_id: current_user.id, finish: 0).pluck(:id)).length
		finishd_task = (Tasktop.where(user_id: current_user.id, finish: 1).pluck(:id)).length
		p finishd_task
		p notyet_task
		taskdata = [['消化済タスク', finishd_task],['未消化タスク', notyet_task]]

		#グラフ描写
		@bar_graph = LazyHighCharts::HighChart.new('graph') do |f|
			f.title(text: 'タスク振り分け状況')
			f.xAxis(categories: team_member)
			f.series(name: 'タスク量(重みの合計)', data: weight_list, type: 'bar')
		end
		@pie_graph = LazyHighCharts::HighChart.new('graph') do |f|
			f.title(text: 'あなたのタスク状況')
			f.series(name: 'タスク', data: taskdata, type: 'pie')
		end
		
		#タスク消化率を計算
		mytask_weight = Tasktop.where(user_id: current_user.id, finish: 1).pluck(:weight).inject(:+)
		teamtask_weight = Tasktop.where(group_id: current_user.group).pluck(:weight).inject(:+)
		p mytask_weight
		p teamtask_weight
		@mytask_digest = mytask_weight.to_f / teamtask_weight.to_f * 100
		@mytask_digest = 0 if mytask_weight == nil
		p @mytask_digest
		
	end

	def index
		@tasktops = Tasktop.where(group_id: current_user.group)
	end

	# GET /tasktops/1
	# GET /tasktops/1.json
	def show
	end

	# GET /tasktops/new
	def new
		@tasktop = Tasktop.new
	end

	# GET /tasktops/1/edit
	def edit
	end

	# POST /tasktops
	# POST /tasktops.json
	def create
		@tasktop = Tasktop.new(tasktop_params)
		@tasktop.weight = 0 if @tasktop.weight == nil
		respond_to do |format|
			if @tasktop.save
				format.html { redirect_to @tasktop, notice: 'タスクが作成されました！' }
				format.json { render action: 'show', status: :created, location: @tasktop }
			else
				format.html { render action: 'new' }
				format.json { render json: @tasktop.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /tasktops/1
	# PATCH/PUT /tasktops/1.json
	def update
		respond_to do |format|
			if @tasktop.update(tasktop_params)
				format.html { redirect_to @tasktop, notice: 'タスクが更新されました！' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @tasktop.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /tasktops/1
	# DELETE /tasktops/1.json
	def destroy
		@tasktop.destroy
		respond_to do |format|
			format.html { redirect_to tasktops_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_tasktop
		@tasktop = Tasktop.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def tasktop_params
		params.require(:tasktop).permit(:name, :weight, :user_id, :group_id, :finish)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasktops_helper.rb
module TasktopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Task" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application" %>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

		<%= javascript_include_tag "application" %>
	</head>
		<body>
			<p class="navbar-text pull-right">
			<% if user_signed_in? %>
				<strong><%= current_user.username %></strong>
				<%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
				<%= link_to "新規登録", new_user_registration_path, :class => 'navbar-link'  %> |
				<%= link_to "ログイン", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
			<div class="navbar navbar-fluid-top">
				<div class="navbar-inner">
					<div class="container-fluid">
						<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>
						<a class="brand" href="/">PBL個人評価システム</a>
						<div class="container-fluid nav-collapse">
							<ul class="nav">
							</ul>
						</div><!--/.nav-collapse -->
					</div>
				</div>
			</div>

			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
						<%= bootstrap_flash %>
						<% if notice %>
							<p class="alert alert-notice"><%= notice %></p>
						<% end %>
						<% if alert %>
							<p class="alert alert-error"><%= alert %></p>
						<% end %>
						<%= yield %>
					</div>
				</div><!--/row-->

				<footer>
				<p>&copy; Company yaginuuu2014</p>
				</footer>

			</div> <!-- /container -->
	</body>
</html>

app/views/tasktops/_form.html.erb
<%= simple_form_for @tasktop, :html => { :class => 'form-horizontal' } do |f| %>
	<%= f.input :name, :label => "タスク名" %>
	<br>
	<br>
	<%= f.input :weight, :label => "タスクの重み" %>
	<br>
	<br>
	タスク担当者を入力してください
	<br>
	<%= f.collection_select :user_id, User.where(group: current_user.group), :id, :username %>
	<br>
	<br>
	<%= f.check_box :finish %>
	<%= p current_user.group %>
	<%= f.hidden_field :group_id, :value => current_user.group %>
	<%= f.submit :登録する, :class => 'btn btn-primary' %>
	<%= link_to "キャンセル", root_path, :class => 'btn' %>
<% end %>

app/views/tasktops/edit.html.erb
<%- model_class = Tasktop -%>
<div class="page-header">
  <h1>タスク編集</h1>
</div>
<%= render :partial => 'form' %>

app/views/tasktops/index.html.erb
<%- model_class = Tasktop -%>
<div class="page-header">
  <h1>タスク一覧</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
		<%= @users %>
      <th>タスク名</th>
      <th>重み</th>
      <th>担当者</th>
			<th>消化済かどうか</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasktops.each do |tasktop| %>
			<% tasktop.finish == 0 ? finish = '未' : finish = '済' %>
      <tr>
        <td><%= link_to tasktop.name, tasktop_path(tasktop) %></td>
        <td><%= tasktop.weight %></td>
        <td><%= tasktop.user.username %></td>
        <td><%= finish %></td>
        <td>
          <%= link_to "編集", edit_tasktop_path(tasktop), :class => 'btn btn-mini' %>
          <%= link_to '削除', tasktop_path(tasktop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '本当に消してもいいですか?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="form-actions">
	<%= link_to "マイページに戻る", root_path, :class => 'btn'  %>
</div>













				

app/views/tasktops/new.html.erb
<%- model_class = Tasktop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', '新規タスク登録'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasktops/show.html.erb
<%- model_class = Tasktop -%>
<div class="page-header">
	<h1>タスク詳細</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>タスク名</th>
			<th>重み</th>
			<th>担当者</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @tasktop.name %></td>
			<td><%= @tasktop.weight %></td>
			<td><%= @tasktop.user.username %></td>
		</tr>
	</tbody>
</table>
<div class="form-actions">
	<%= link_to "マイページに戻る", root_path, :class => 'btn'  %>
	<%= link_to "タスク一覧", tasktops_path, :class => 'btn'  %>
	<%= link_to "タスクを編集", edit_tasktop_path(@tasktop), :class => 'btn' %>
	<%= link_to "タスクを削除", tasktop_path(@tasktop),
		:method => 'delete',
		:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '本当に消しますか?')) },
		:class => 'btn btn-danger' %>
	</div>

app/views/tasktops/top.html.erb
<h2>チーム<%= current_user.group %></h2>
<div id="container">
	<div id="head">
		<%= high_chart("team", @bar_graph) %>
	</div>
	<div id="left_g">
		<%= high_chart("my", @pie_graph) %>
	</div>
	<div id="right_g"; align="center"> 
		<h2>あなたのタスク消化率は</h2>
		<font size="7" color="red">約<%= @mytask_digest.to_i %>%</font><font size="5"><b>です</b></font>
	</div>
	<div id="new" align="center">
		<%= link_to "新規タスク登録", new_tasktop_path, :class => 'btn btn-primary btn-large' %>
		<%= link_to "タスク一覧", tasktops_path, :class => 'btn btn-primary btn-large' %>
	</div>


						
</div>